//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _26_ProductWebApp.ProductService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.com/ProductService", ConfigurationName="ProductService.ProductServiceSoap")]
    public interface ProductServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetProductDetailsResult from namespace http://www.example.com/ProductService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/ProductService/GetProductDetails", ReplyAction="*")]
        _26_ProductWebApp.ProductService.GetProductDetailsResponse GetProductDetails(_26_ProductWebApp.ProductService.GetProductDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.com/ProductService/GetProductDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<_26_ProductWebApp.ProductService.GetProductDetailsResponse> GetProductDetailsAsync(_26_ProductWebApp.ProductService.GetProductDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductDetails", Namespace="http://www.example.com/ProductService", Order=0)]
        public _26_ProductWebApp.ProductService.GetProductDetailsRequestBody Body;
        
        public GetProductDetailsRequest() {
        }
        
        public GetProductDetailsRequest(_26_ProductWebApp.ProductService.GetProductDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.example.com/ProductService")]
    public partial class GetProductDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int productId;
        
        public GetProductDetailsRequestBody() {
        }
        
        public GetProductDetailsRequestBody(int productId) {
            this.productId = productId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductDetailsResponse", Namespace="http://www.example.com/ProductService", Order=0)]
        public _26_ProductWebApp.ProductService.GetProductDetailsResponseBody Body;
        
        public GetProductDetailsResponse() {
        }
        
        public GetProductDetailsResponse(_26_ProductWebApp.ProductService.GetProductDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.example.com/ProductService")]
    public partial class GetProductDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetProductDetailsResult;
        
        public GetProductDetailsResponseBody() {
        }
        
        public GetProductDetailsResponseBody(System.Xml.Linq.XElement GetProductDetailsResult) {
            this.GetProductDetailsResult = GetProductDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductServiceSoapChannel : _26_ProductWebApp.ProductService.ProductServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceSoapClient : System.ServiceModel.ClientBase<_26_ProductWebApp.ProductService.ProductServiceSoap>, _26_ProductWebApp.ProductService.ProductServiceSoap {
        
        public ProductServiceSoapClient() {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _26_ProductWebApp.ProductService.GetProductDetailsResponse _26_ProductWebApp.ProductService.ProductServiceSoap.GetProductDetails(_26_ProductWebApp.ProductService.GetProductDetailsRequest request) {
            return base.Channel.GetProductDetails(request);
        }
        
        public System.Xml.Linq.XElement GetProductDetails(int productId) {
            _26_ProductWebApp.ProductService.GetProductDetailsRequest inValue = new _26_ProductWebApp.ProductService.GetProductDetailsRequest();
            inValue.Body = new _26_ProductWebApp.ProductService.GetProductDetailsRequestBody();
            inValue.Body.productId = productId;
            _26_ProductWebApp.ProductService.GetProductDetailsResponse retVal = ((_26_ProductWebApp.ProductService.ProductServiceSoap)(this)).GetProductDetails(inValue);
            return retVal.Body.GetProductDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_26_ProductWebApp.ProductService.GetProductDetailsResponse> _26_ProductWebApp.ProductService.ProductServiceSoap.GetProductDetailsAsync(_26_ProductWebApp.ProductService.GetProductDetailsRequest request) {
            return base.Channel.GetProductDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<_26_ProductWebApp.ProductService.GetProductDetailsResponse> GetProductDetailsAsync(int productId) {
            _26_ProductWebApp.ProductService.GetProductDetailsRequest inValue = new _26_ProductWebApp.ProductService.GetProductDetailsRequest();
            inValue.Body = new _26_ProductWebApp.ProductService.GetProductDetailsRequestBody();
            inValue.Body.productId = productId;
            return ((_26_ProductWebApp.ProductService.ProductServiceSoap)(this)).GetProductDetailsAsync(inValue);
        }
    }
}
