//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleInterestClient.SimpleInterestWCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SimpleInterestWCFService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateSimpleInterest", ReplyAction="http://tempuri.org/IService1/CalculateSimpleInterestResponse")]
        double CalculateSimpleInterest(double principal, double rate, double time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateSimpleInterest", ReplyAction="http://tempuri.org/IService1/CalculateSimpleInterestResponse")]
        System.Threading.Tasks.Task<double> CalculateSimpleInterestAsync(double principal, double rate, double time);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SimpleInterestClient.SimpleInterestWCFService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SimpleInterestClient.SimpleInterestWCFService.IService1>, SimpleInterestClient.SimpleInterestWCFService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalculateSimpleInterest(double principal, double rate, double time) {
            return base.Channel.CalculateSimpleInterest(principal, rate, time);
        }
        
        public System.Threading.Tasks.Task<double> CalculateSimpleInterestAsync(double principal, double rate, double time) {
            return base.Channel.CalculateSimpleInterestAsync(principal, rate, time);
        }
    }
}
